FROM confluentinc/cp-kafka-connect-base:5.4.1
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-rabbitmq:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-kudu:latest
